# config.yaml
# William L. Close

# Purpose: Snakemake config file containing user-provided settings for analyzing Swift Amplicon 16S™+ITS Panel
# data using mothur phylotype-based approach.

##################################################################
#
# Mothur
#
##################################################################

# NOTE: As required, change these settings before running workflow.

# Group names of mock samples (e.g. Mock1_S1_L001_R1_001.fastq.gz = Mock1).
# NOTE: If you don't have any mock samples, keep heading but delete list items underneath heading.
mothurMock:
  - KPMSA10031ng1

# Group names of control samples (e.g. Water1_S2_L001_R1_001.fastq.gz = Water1).
# NOTE: If you don't have any control samples, keep heading but delete list items underneath heading.
mothurControl:
  - 16SntcLRQC3

# Desired alpha diversity metrics.
mothurAlpha:
  - nseqs
  - coverage
  - invsimpson
  - shannon
  - sobs

# Desired beta diversity metrics.
mothurBeta:
  - sharedsobs
  - thetayc
  - braycurtis

# Minimum read threshold for subsampling.
subthresh: 1000



# NOTE: Leave these settings as is.

# Read numbers
readNum:
  - R1
  - R2

# Random seed
seed: 20170415
